// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczBlIYidvuRNoiYYpWe-6CeYBa5l_d14',
    appId: '1:60331246835:web:c3225b406e8c879a0da386',
    messagingSenderId: '60331246835',
    projectId: 'learn-flutter-202',
    authDomain: 'learn-flutter-202.firebaseapp.com',
    storageBucket: 'learn-flutter-202.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ub0l39xxlmUnFVBVU42RchDI76WTyiA',
    appId: '1:60331246835:android:602cd8d3565b485a0da386',
    messagingSenderId: '60331246835',
    projectId: 'learn-flutter-202',
    storageBucket: 'learn-flutter-202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYA9mk3NrGmX_efjMbJJxcslDi5rsdHNo',
    appId: '1:60331246835:ios:1bbdceb61079941c0da386',
    messagingSenderId: '60331246835',
    projectId: 'learn-flutter-202',
    storageBucket: 'learn-flutter-202.firebasestorage.app',
    iosBundleId: 'com.example.angel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYA9mk3NrGmX_efjMbJJxcslDi5rsdHNo',
    appId: '1:60331246835:ios:1bbdceb61079941c0da386',
    messagingSenderId: '60331246835',
    projectId: 'learn-flutter-202',
    storageBucket: 'learn-flutter-202.firebasestorage.app',
    iosBundleId: 'com.example.angel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDczBlIYidvuRNoiYYpWe-6CeYBa5l_d14',
    appId: '1:60331246835:web:0cf0ad8f1c32378f0da386',
    messagingSenderId: '60331246835',
    projectId: 'learn-flutter-202',
    authDomain: 'learn-flutter-202.firebaseapp.com',
    storageBucket: 'learn-flutter-202.firebasestorage.app',
  );
}
